FROM mcr.microsoft.com/dotnet/sdk:2.1 as build

WORKDIR /app

COPY . ./

RUN dotnet publish aula21.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:2.1
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "aula21.dll"]
